### ISSUE TITLE
Version 0.8.0 is not setting csp_nonce correctly

### ISSUE THREAD

**Issue by tunetheweb** [wntrblm/flask-talisman#12]
I've introduced a bug in https://github.com/GoogleCloudPlatform/flask-talisman/pull/18 where the `content_security_policy_nonce_in` being set for any CSP directive, means it's set on all directives.

So this:

```py
talisman = Talisman(
    app,
    content_security_policy=csp,
    content_security_policy_nonce_in=['script-src']
)
```

Sets the nonce on `script-src` and `style-src` and every other directive.

Preparing a pull request and test case to catch this in future. We should probably release this ASAP.

**Comment by Jonakemon** [comment]
Thanks Barry! If you tag meij the PR I'll review it immediately.

-------- Original Message --------

**Comment by Jonakemon** [comment]
@tunetheweb fix was released just now, thanks Barry!
